DROP TABLE course_student;
DROP TABLE address;
DROP TABLE course;
DROP TABLE student;
DROP TABLE lecturer;

CREATE TABLE address (
  id     INT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  zip    VARCHAR(10)  DEFAULT NULL,
  state  VARCHAR(50)  DEFAULT NULL,
  street VARCHAR(50)  DEFAULT NULL,
  city   VARCHAR(50)  DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE course (
  id       INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  name     VARCHAR(100) NOT NULL,
  lecturer VARCHAR(50)  NOT NULL,
  type     VARCHAR(11)  NOT NULL,
  mark     INT,
  PRIMARY KEY (id)
);

CREATE TABLE student (
  id         INT         NOT NULL GENERATED ALWAYS AS IDENTITY,
  first_name VARCHAR(50) NOT NULL,
  last_name  VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE course_student (
  course_id             INT NOT NULL,
  student_id            INT NOT NULL,
  course_student_ibfk_1 INT CONSTRAINT course_fk REFERENCES course
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  course_student_ibfk_2 INT CONSTRAINT student_fk REFERENCES student
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);

CREATE TABLE lecturer (
  first_name VARCHAR(50) NOT NULL,
  last_name  VARCHAR(50) NOT NULL,
  PRIMARY KEY (first_name, last_name)
);
